### PR TITLE
Verify that the intent will resolve to an activity.

### PR DESCRIPTION
**Pull request by daveliu0301**

### CODE REVIEW

**Comment by daveliu0301** [comment]
Thanks for your help. I signed it.

**Comment by daveliu0301** [comment]
I downloaded Google APIs, and signed in Travis CI with my github account, flicked this repository switch on. should I push again?

**Comment by tasomaniac** [comment]
I wouldn't try to fix Travis in this PR. It is unrelated and wouldn't change much. I guess all the PRs would fail in the repo.

**Comment by daveliu0301** [comment]
all right. Travis almost makes me crazy, hah hah. thank you.

**Pull request closed without merging**
