### PR TITLE
Background click effect and margin-left in the first Tab

### PR DESCRIPTION
**Pull request by douglasjunior**
- Added background click effect also for custom view.
- Added margin-left in the first Tab. According to guideline https://www.google.com/design/spec/components/tabs.html#tabs-specs

### CODE REVIEW

**Comment by douglasjunior** [comment]
I signed it!

**Comment by PaulRashidi** [comment]
Closing this as I think this is better implemented in the design support library and RTL would need to be supported (START rather than LEFT).

**Comment by douglasjunior** [comment]
Ok, thanks.

**Comment by PaulRashidi** [comment]
Thank you as well. If you wanted to help out with the design library it's located in android source at https://android.googlesource.com/platform/frameworks/support/+/marshmallow-release (design sub-directory).  Contributing patch info here: https://source.android.com/source/submit-patches.html And I usually suggest opening a bug to discuss the change before embarking on the change.

**Comment by douglasjunior** [comment]
Nice. Thanks for the tips. :smiley:

**Pull request closed without merging**
