### PR TITLE
Fixing issue: "Error:(20,0) No such property. model for class". Updated Travis config and Gradle files

### PR DESCRIPTION
**Pull request by piotrek1543**
Hi, I deleted signingConfings. It makes an error on first build after cloning repository and moreover, I don't feel it is necessary for this app which would it be rather used for testing, discovering new things, learning to code from the best.

### CODE REVIEW

**Comment by piotrek1543** [comment]
I signed it!

**Comment by ardock** [comment]
Your first build failed due you didn't follow [the step 6 of the building instructions](https://github.com/google/iosched/blob/master/doc/BUILDING.md):

> 6 . Add your debug keystore to the project (save it as android/debug.keystore), or modify the build.gradle file to point to your key.

Your pull request failed due an outdated travis-ci configuration and [my pending pull request](https://github.com/google/iosched/pull/156) fixes it and depends on the part you try to remove.

I know they don't use it internally and no need our contributions, they only share the source as a sample, but would be nice that our pull requests could be automatically checked.

**Comment by piotrek1543** [comment]
I signed it!

**Comment by ardock** [comment]
> Hi, I deleted signingConfings.

Why?

> **I don't** feel it is necessary...

I do.

Did you set up the [server side](https://github.com/google/iosched/blob/master/doc/BUILDING.md#server-side-setup)?

**Comment by piotrek1543** [comment]
@ardock what's wrong you with you? Said it properly and clearly or don't.

About "server" side:
###These steps are optional, in the sense that IOSched will build and run even if you don't set up the server side.

**Comment by eneim** [comment]
I think he meant that the ```signConfig``` was there by purpose, and it was an important part of this project where you should not delete. In fact, you should and definitely should keep it and modify that part in case you want to create your own Conference Helper Client (an adoption of this Project). So take care of your signing config.

**Comment by piotrek1543** [comment]
@eneim did you read my answer to @ardock ?

**Comment by eneim** [comment]
@piotrek1543 I update my answer. The point is @ardock doesn't encourage you to remove the signConfig in the project.

**Comment by piotrek1543** [comment]
@eneim  @ardock  Ok, I returned deleted statements and changed name of commit

**Comment by piotrek1543** [comment]
I also updated Gradle files. Hope you enjoy this.

**Comment by ardock** [comment]
Thanks @eneim, that was my opinion. 3000+ forks, we can do this type of changes in our forks.
Sorry @piotrek1543, I never used Genymotion but searching this on Google, first two results seem useful:
> Genymotion. Server side depends on Google services
[How to install Google Play Services on Genymotion Step by Step](http://inthecheesefactory.com/blog/how-to-install-google-services-on-genymotion/en)
[Google Play Services in Genymotion on Lollipop (Android 5.0)](http://stackoverflow.com/questions/27045599/google-play-services-in-genymotion-on-lollipop-android-5-0)

**Comment by piotrek1543** [comment]
@ardock, thanks for help and comment

**Comment by ardock** [comment]
@piotrek1543 You are welcome, and sorry about that, I didn't understand the change and I'm not fluent in English, good luck Eneim translates me :).

**Pull request closed without merging**
