### PR TITLE
Optimised image files

### PR DESCRIPTION
**Pull request by konifar**
Some icons were not optimized.
So I optimized icons by using [ImageOptim](https://imageoptim.com/).

After optimized, the icons size is reduced 33.4% on average.

imageoptim

### CODE REVIEW

**Comment by konifar** [comment]
CI failed. But I don't know why. Could you help? :bow: 
https://travis-ci.org/google/iosched/builds/114851359

```
$ ./scripts/wait_for_emulator.sh
/home/travis/build.sh: line 45: ./scripts/wait_for_emulator.sh: No such file or directory
The command "./scripts/wait_for_emulator.sh" failed and exited with 127 during .
Your build has been stopped.
```

**Comment by eneim** [comment]
@konifar This is how I made it works. You can copy-paste and see the diff to know the changes.

https://github.com/eneim/iosched/blob/master/.travis.yml

**Comment by konifar** [comment]
@eneim Oh thanks! I'll try it!

**Comment by eneim** [comment]
It seems that your build tool version is not fit current script's version, just fix it and I think i would work.

> https://github.com/konifar/iosched/blob/master/android/build.gradle#L35

**Comment by konifar** [comment]
CI fixed. Could you review this?

**Comment by rachitmishra** [comment]
isn't this already done by `shrinkResources true`

**Comment by eveliotc** [comment]
yup see also if you pre-optimize changes are aapt might even inflate see https://medium.com/@duhroach/smaller-pngs-and-android-s-aapt-tool-4ce38a24019d#.9y7h89prw

**Pull request closed without merging**
