### PR TITLE
Minor improvements to PR https://github.com/google/iosched/pull/376

### PR DESCRIPTION
**Pull request by tikurahul**
* Builds upon the great work in https://github.com/google/iosched/pull/376.
* Addresses a new minor issues.

Test: `./gradlew check`.

### CODE REVIEW

**Comment by JoseAlcerreca** [comment]
@nuhkoca can you do the `@googlebot I consent` bit here?

**Comment by nuhkoca** [comment]
@googlebot I consent

**Comment by JoseAlcerreca** [comment]
@nuhkoca are you happy with the changes?

**Comment by nuhkoca** [comment]
@JoseAlcerreca definitely! Thanks for your help on this. Looking forward to this.

**Comment by JoseAlcerreca** [comment]
Thanks both!

**Pull request merged**
