### PR TITLE
Update SlidingTabLayout.java

### PR DESCRIPTION
**Pull request by helloooideeeeea**
A function added.
It used to change Tab Header Text dynamically when Swiped or Tab Clicked.

From a pull request virgin.

### CODE REVIEW

**Comment by helloooideeeeea** [comment]
I signed it!

**Comment by PaulRashidi** [comment]
I'll need to review against our upcoming changes w.r.t. the 2015 version source code release. Expect a day or two delay.

Thanks,

Paul

**Comment by helloooideeeeea** [comment]
Hi.
>Expect a day or two delay.
OK. Thank you.
I didn't should do the second time of commit.
Interface method parameter's View might not be necessary, because I think it doesn't use anyone.
so I would appreciate if you do merge first time of commit(commit number #b06dbf4).
thanks!

**Comment by helloooideeeeea** [comment]
Hi, Paul.
Updated SlidingTabLayout.java again.
it's change that return b09ec14' source code and light fix.
thanks!

**Comment by PaulRashidi** [comment]
Sorry for the delay. Please rebase and I'll review.

**Pull request closed without merging**
